name: R-CMD-check ANTsRNet

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-22.04

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      # 🧠 Cache R packages
      - name: Cache R packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-pkgs-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-r-pkgs-

      # 🧠 Cache ANTsR GitHub install
      - name: Cache ANTsR build
        uses: actions/cache@v3
        with:
          path: ~/.local/share/R/ANTsR
          key: ${{ runner.os }}-antsr-build-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-antsr-build-

      # 🧠 Cache TensorFlow installation
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: ~/.local/share/r-reticulate
          key: ${{ runner.os }}-tf2-py-${{ hashFiles('DESCRIPTION') }}
          restore-keys: |
            ${{ runner.os }}-tf2-py-

      - name: Install R dependencies
        run: |
          Rscript -e 'install.packages(c("remotes", "testthat", "tensorflow"), repos = "https://cloud.r-project.org")'

      - name: Install Miniconda via reticulate
        run: |
          Rscript -e 'reticulate::install_miniconda()'

      - name: Confirm Python configuration
        run: |
          Rscript -e 'reticulate::use_miniconda("r-reticulate", required = TRUE)'
          Rscript -e 'reticulate::py_config()'

      - name: Install TensorFlow
        run: |
          Rscript -e 'tensorflow::install_tensorflow(version = "2.9.1")'

      - name: Configure GitHub PAT
        run: |
          echo "GITHUB_PAT=${{ secrets.GH_PAT }}" >> $GITHUB_ENV
          echo "GITHUB_PAT=${{ secrets.GH_PAT }}" >> ~/.Renviron

      - name: Install ANTsR
        run: |
          mkdir -p ~/.local/share/R/ANTsR && cd ~/.local/share/R/ANTsR
          Rscript -e 'remotes::install_github("ANTsX/ANTsR", dependencies = TRUE)'

      - name: Install ANTsRNet
        run: |
          Rscript -e 'remotes::install_local(".", dependencies = TRUE)'

      - name: Confirm Python + reticulate config
        run: |
          Rscript -e 'reticulate::py_config()'

      - name: Run tests
        run: |
          Rscript -e 'testthat::test_dir("tests/testthat", reporter = testthat::SummaryReporter$new())'
